{
    'name': 'ServiceHub',
    'version': '17.0.1.0.0',
    'category': 'Services/Services',
    'summary': 'مدیریت سرویس های شرکت آرکا',
    'description': 'مدیریت سرویس های شرکت آرکا',
    'author': 'مهدی صیادی',
    'license': 'LGPL-3',
    'depends': ['base'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'views/service_order_views.xml',
        'views/service_type_views.xml',
        'views/service_tag_views.xml',
        'views/service_menus.xml',
    ],
    'application': True,
    'installable': True,
}
